### ISSUE TITLE
Invalid date for staking transactions

### ISSUE THREAD

**Issue by fedekunze** [cosmos/lunie#2250] opened 2019-03-13 10:17 UTC
**Describe the bug**

Dates from staking transactions are updated somewhere after creation and thus the date becomes invalid.

Added a bug handler in the meantime on #2185. 

**To Reproduce**

1. Create a staking transaction
2. Go to Transactions Page (Date is OK)
3. Go to another page
4. Go once again to transactions page (Date is broken)

**Expected behavior**

Tx time shouldn't be updated

**Comment by fedekunze** [comment] 2019-03-13 10:18
Note: This is not the case for block page's transactions

**Comment by jbibla** [comment] 2019-03-13 11:39
i thought we addressed this with updating txs individually instead of every block?

**Comment by faboweb** [comment] 2019-03-20 14:16
I can't reproduce this.

**Comment by faboweb** [comment] 2019-03-20 14:24
Seems fixed on develop

**Comment by fedekunze** [comment] 2019-03-25 10:15
No it's not (just reproduced). You need to follow the steps from above

**Comment by faboweb** [comment] 2019-03-25 14:16
Tested on staging and I can't reproduce with the steps above.

**Comment by fedekunze** [comment] 2019-03-25 14:22
I tested it on localhost (develop)

**Comment by faboweb** [comment] 2019-03-25 14:25
Ok reproduced

**Closed** 2019-03-26 14:23 UTC
Labels: bug :bug:
